CREATE DATABASE IF NOT EXISTS `auth_db`;
CREATE DATABASE IF NOT EXISTS `auction_db`;
CREATE DATABASE IF NOT EXISTS `bidding_db`;
CREATE DATABASE IF NOT EXISTS `payment_db`;

GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'rootpassword';
FLUSH PRIVILEGES;
